baseURL: "http://example.org/"
title: "CorrelAid"
DefaultContentLanguage: de
copyright: Everything is mine
languages:
  en:
    contentDir: content/en
    title: CorrelAid
    weight: 2
  de:
    contentDir: content/de
    title: CorrelAid
    weight: 1
