baseURL                 = "https://correlaid.org/"

DefaultContentLanguage  = "de"

PygmentsCodeFences      = true
PygmentsStyle           = "friendly"

[Languages]
[Languages.en]
    contentDir      = "content/en"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "English"
    [Languages.en.params]
        [Languages.en.params.navigation]
            about   = "About"

[Languages.de]
    contentDir      = "content/de"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "Deutsch"
    [Languages.de.params]
            [Languages.de.params.navigation]
                about   = "Über uns"
[Languages.fr]
    contentDir      = "content/fr"
    title           = "CorrelAid"
    weight          = 0
    languageName    = "French"
    [Languages.fr.params]
            [Languages.fr.params.navigation]
                about   = "A propos"
