baseURL: "http://example.org/"
title: "CorrelAid"
DefaultContentLanguage: de
copyright: Everything is mine
languages:
  en:
    contentDir: content/english
    title: CorrelAid
    weight: 2
  de:
    contentDir: content/german
    title: CorrelAid
    weight: 1
